#include "../include/stygian_editor.h"

#include <math.h>
#include <stdio.h>
#include <string.h>

int main(void) {
  StygianEditorConfig cfg = stygian_editor_config_default();
  StygianEditor *editor = stygian_editor_create(&cfg, NULL);
  StygianEditorRectDesc slider = {0};
  StygianEditorRectDesc box = {0};
  StygianEditorBehaviorRule rule = {0};
  StygianEditorNodeId slider_id;
  StygianEditorNodeId box_id;
  char code_out[32768];
  size_t required;

  if (!editor)
    return 1;

  slider.x = 32.0f;
  slider.y = 640.0f;
  slider.w = 280.0f;
  slider.h = 24.0f;
  slider.radius[0] = 12.0f;
  slider.radius[1] = 12.0f;
  slider.radius[2] = 12.0f;
  slider.radius[3] = 12.0f;
  slider.fill = stygian_editor_color_rgba(0.20f, 0.26f, 0.33f, 1.0f);
  slider.visible = true;
  slider.z = 1.0f;
  slider_id = stygian_editor_add_rect(editor, &slider);

  box.x = 420.0f;
  box.y = 640.0f;
  box.w = 220.0f;
  box.h = 120.0f;
  box.radius[0] = 14.0f;
  box.radius[1] = 14.0f;
  box.radius[2] = 14.0f;
  box.radius[3] = 14.0f;
  box.fill = stygian_editor_color_rgba(0.14f, 0.52f, 0.91f, 1.0f);
  box.visible = true;
  box.z = 2.0f;
  box_id = stygian_editor_add_rect(editor, &box);

  memset(&rule, 0, sizeof(rule));
  rule.trigger_node = slider_id;
  rule.trigger_event = STYGIAN_EDITOR_EVENT_PRESS;
  rule.action_kind = STYGIAN_EDITOR_ACTION_ANIMATE;
  rule.animate.target_node = box_id;
  rule.animate.property = STYGIAN_EDITOR_PROP_Y;
  rule.animate.from_value = NAN;
  rule.animate.to_value = 40.0f;
  rule.animate.duration_ms = 350u;
  rule.animate.easing = STYGIAN_EDITOR_EASING_OUT_CUBIC;
  stygian_editor_add_behavior(editor, &rule, NULL);

  required = stygian_editor_build_c23(editor, code_out, sizeof(code_out));
  printf("generated bytes: %zu\n\n", required);
  puts(code_out);

  stygian_editor_destroy(editor);
  return 0;
}
